Repository Firesphere/silverstripe-solr-search, pull requests merged in 2019-12, with the labels that each got.

#147 Stemming fixes, finally
  Solr/4/templates/schema.ss
  Solr/5/templates/schema.ss
  Solr/5/templates/types.ss
  docs/01-Changelog.md
  docs/01-Installation.md
  docs/02-Solr.md
  docs/03-Usage.md
  docs/04-Customisation.md
  docs/05-CMS-Usage.md
  docs/06-Fulltext-Search-Compatibility.md
  docs/07-Debugging.md
  docs/08-Suggestions.md
  docs/09-Elemental.md
  docs/13-Changelog.md
  docs/14-About.md
  docs/index.md
  src/Indexes/BaseIndex.php
  tests/unit/BaseIndexTest.php
Labels: enhancement

#154 Improved group-based view status indexing
  composer.json
  docs/01-Installation.md
  docs/03-Usage.md
  docs/04-Customisation.md
  docs/06-Fulltext-Search-Compatibility.md
  docs/07-Debugging.md
  docs/10-View-Permissions.md
  docs/13-Changelog.md
  docs/index.md
  src/Extensions/DataObjectExtension.php
  src/Helpers/SolrLogger.php
  src/Indexes/BaseIndex.php
  src/Tasks/ClearErrorsTask.php
  src/Traits/QueryComponentTraits/QueryComponentFilterTrait.php
  tests/unit/BaseIndexTest.php
  tests/unit/DataObjectExtensionTest.php
  tests/unit/SolrLoggerTest.php
Labels: enhancement

#156 Fixes for faceting on the wrong base class
  .circleci/TestIndexTwo.yml
  docs/03-Usage.md
  docs/template.html
  src/Extensions/DataObjectExtension.php
  src/Indexes/BaseIndex.php
  src/Traits/QueryComponentTraits/QueryComponentFacetTrait.php
  tests/mocks/TestIndex.php
  tests/unit/BaseIndexTest.php
Labels: Blocker, Bugfix, High priority, bug

#161 FIX: Fixes #160 by passing `false` to PaginatedList::setLimitItems()
  src/Results/SearchResult.php
Labels: bug

#159 Fix deprecations on Solr7+
  .circleci/config.yml
  Solr/7/extras/elevate.xml
  Solr/7/extras/mapping-FoldToASCII.txt
  Solr/7/extras/protwords.txt
  Solr/7/extras/solrconfig.xml
  Solr/7/extras/stopwords.txt
  Solr/7/templates/schema.ss
  Solr/7/templates/types.ss
  _config/solr.yml
  docs/03-Usage.md
  docs/16-Known-issues.md
  docs/17-code-stats.md
  docs/index.md
  src/Indexes/BaseIndex.php
  src/Services/SolrCoreService.php
  src/Tasks/SolrIndexTask.php
  src/Traits/GetterSetterTrait.php
  tests/mocks/TestIndexThree.php
  tests/unit/DataResolverTest.php
  tests/unit/SolrConfigureJobTest.php
  tests/unit/SolrConfigureTaskTest.php
  tests/unit/SolrCoreServiceTest.php
  tests/unit/SolrIndexTaskTest.php
  tests/unit/SolrLoggerTest.php
Labels: Low priority

#171 [Bug] Fix quotes
  src/Factories/QueryComponentFactory.php
  tests/unit/QueryComponentFactoryTest.php
Labels: High priority, bug

#170 [bugfix] Fix faceting bug and docs
  docs/02-Solr.md
  docs/03-Usage.md
  docs/04-Advanced-Options/01-Faceting.md
  docs/04-Advanced-Options/02-Boosting.md
  docs/04-Advanced-Options/03-Fuzzy-search.md
  docs/04-Advanced-Options/04-Elevation.md
  docs/05-Customisation.md
  docs/06-CMS-Usage.md
  docs/07-Debugging.md
  docs/08-Suggestions.md
  docs/09-View-Permissions.md
  docs/10-Submodules/01-Fulltext-Search-Compatibility.md
  docs/10-Submodules/02-Subsites.md
  docs/10-Submodules/03-Fluent.md
  docs/10-Submodules/04-Member-based-permissions.md
  docs/10-Submodules/05-Elemental.md
  docs/11-Contributing/01-Code-of-Conduct.md
  docs/11-Contributing/02-Contributing.md
  docs/12-Help/01-Changelog.md
  docs/12-Help/02-FAQ.md
  docs/12-Help/03-Known-issues.md
  docs/13-About/01-About.md
  docs/13-About/02-Coverage.md
  docs/13-About/03-Codebase-stats.md
  docs/13-About/04-Plans.md
  docs/index.md
  src/Traits/QueryComponentTraits/QueryComponentFacetTrait.php
Labels: Bugfix, enhancement

#182 Hans/update fixes
  src/Tasks/ClearDirtyClassesTask.php
  src/Tasks/SolrIndexTask.php
Labels: bug

#184 Throw the actual error instead of continue
  .circleci/config.yml
  src/Indexes/BaseIndex.php
Labels: Bugfix
